project:
  type: website
  output-dir: docs  

website:
  title: "Exam6"
  navbar:
    left:
      - tivkias.qmd
      - saznsd.qmd
      - uuibias.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

