---
title: "Системы аутентификации и защита информации от несанкционированного доступа"
---

1.  **Понятие угрозы безопасности информации. Основные угрозы безопасности автоматизированной системе.**

2.  **Понятие безопасности и уязвимости информационной системы, виды уязвимостей.**

3.  **Понятия конфиденциальности, целостности и доступности.**

4.  **Понятие уязвимости проектирования, примеры. Понятие эксплойта, виды эксплойтов.\
    **0-day - опасна, ничем не закрыть, кроме выключения порта\
    1-day - решение уже вышло, но пользователь не установил обновление
    Уязвимости проектирования -- ошибки допущенные при построении архитектуры программного продукта, протокола, устройства (например, передача всех данных в открытом виде в протоколах Telnet, HTTP, FTP). То есть, те ошибки которые допустили архитекторы и проектировщики решения при построении его архитектуры.

    RCE - удаленное выполнение кода\
    LPE - локальное повышение привилегий\
    Sandbox Escape - результат эксплуатации уязвимостей, позволяющих из изолированной среды --- песочницы --- выполнить вредоносный код за ее пределами.\
    Эксплойты --- это подвид вредоносных программ. Они содержат данные или исполняемый код, способный воспользоваться одной или несколькими [уязвимостями](https://encyclopedia.kaspersky.ru/glossary/vulnerability/?utm_source=kdaily&utm_medium=blog&utm_campaign=termin-explanation) в программном обеспечении на локальном или удаленном компьютере. [эксплоит.касперский](https://kaspersky-ru.turbopages.org/kaspersky.ru/s/blog/exploits-problem-explanation/8459/)\
    Пример: Nuclear Pack  --- поражает жертв эксплойтами Java и Adobe PDF, а также подсаживает Caphaw --- печально известный банковский [троян](https://encyclopedia.kaspersky.ru/glossary/trojan/?utm_source=kdaily&utm_medium=blog&utm_campaign=termin-explanation) .

5.  **Понятие уязвимости реализации, примеры. Понятие эксплойта, виды эксплойтов.\
    **

6.  **Понятие уязвимости конфигурации, примеры. Понятие эксплойта, виды эксплойтов.**

7.  **Модели внешних преднамеренных угроз информационной безопасности. Основные этапы методологии MITRE ATT&CK.\
    ***(Это база знаний с тактиками, техниками, процедурами. матрица enterprise, у каждой техники есть ID)* **\
    ***Reconnaissance - разведка\
    Initial access - первоначальный доступ\
    Execution - выполнение кода\
    Persistence - закрепление\
    Privilege Escalation - повышение привилегий (запускаем)\
    Defence Evasion - есть СЗИ, техники\
    Credential Access - логины, пароли\
    Discovery - обнаружение, что в закладках сложено (Windows Active Directory, контроллер домена)\
    Lateral Movement - горизонтальное перемещение\
    Collection - сбор информации\
    Command and control - как организовать централизованное управление агентами\
    Exfiltration - незаметное извлечение данных из внутренней системы организации (обмануть DLP)\
    Impact - выкачивание файлов, выложить в открытый доступ*

8.  **Модели внешних преднамеренных угроз информационной безопасности. Основные этапы методологии Penetration Testing Execution Standard.\
    ***Pre-engagement Interactions (подготовка меропр.)\
    Intelligence Gathering (сбор информации)\
    Vulnerability Analysis (анализ уязвимостей)\
    Exploitation (эксплуатация)\
    Post Exploitation (постэксплуатация)\
    Reporting (разработка отчетности)*

9.  **Модели внешних преднамеренных угроз информационной безопасности. Основные этапы методологии Lockheed Martin Cyber Kill Chain.\
    ***Reconnaisance (разведка)\
    Weaponization (вооружение???)\
    Delivery \
    Exploitation\
    Installation\
    Command & Control\
    Actions on objects*

10. **Понятие OSINT. Цели, методы, средства проведения OSINT.**

11. **Понятие поиска и анализа уязвимостей. Цели, методы и средства.**

12. **Уязвимости веб-приложений. Уязвимости OWASP Top 10.**

13. **Назначение и основные функции TIP OpenCTI.**

14. **Назначение и основные функции Zeek.**

15. **Встроенные средства опреационной системы Linux для сбора информации о состоянии вычислительной системы.**

16. **Защита от локального НСД. Типовые практики защиты.**

17. **Защита от атак уровня приложений. Web Application Firewall.**

18. **Защита от атак уровня приложений. Database Access Firewall.**

19. **Понятие компрометации через цепочки поставок. Примеры.**

20. **Понятие перечня компонентов программного обеспечения (SBOM -- Software Bill of Materials). Форматы описания SBOM.**

21. **Мониторинг информационной безопасности. Виды источников информации для мониторинга.**

22. **Мониторинг информационной безопасности. Средства сбора информации о сетевых событиях.**

23. **Мониторинг информационной безопасности. ELK Stack, Opensearch -- состав, назначение.**

24. **Система стандартов в области защиты информации: структура, назначение, основные понятия.**

25. **Система стандартов в области защиты информации. ГОСТ Р 58833-2020: структура, назначение, основные понятия.**

26. **Система стандартов в области защиты информации. ГОСТ Р 58833-2020. Виды аутентификации.**

27. **Система стандартов в области защиты информации. Уровни доверия аутентификации. Нормативные документы.**

28. **Сетевые средства защиты информационных систем.**

29. **Понятие хоста. Хостовые средства защиты информационных систем.**

30. **Понятие воспроизводимых исследований и воспроизводимых отчетов. Основные программные средства обеспечения воспроизводимых исследований.**

## 
