---
title: "Угрозы и уязвимости ИБ ИАС"
---

1.  **Определения «система», «автоматизированная информационная система», «система передачи данных»**
2.  **Что такое Модель OSI? Ее уровни**
3.  **Функции каждого уровня модели OSI**
4.  **Различие модели OSI и стека протоколов TCP/IP**
5.  **Примеры протоколов по каждому уровню стека протоколов TCP/IP**
6.  **Что такое АСУ ТП? Примеры кибератак**
7.  **Что такое информационно-аналитические системы, их функции**
8.  **Признаки и компоненты ИАС**
9.  **Что такое СОВ (системы обнаружения вторжений)? Классификация СОВ**
10. **Типовая архитектура системы обнаружения вторжений. Примеры СОВ**
11. **Что такое DDP-системы (системы распределенной инфраструктуры ложных целей)? Примеры программных решений**
12. **Что такое модель Cyber Kill Chain?**
13. **Что такое APT-атака? Примеры целевых атак**
14. **Примеры систем защиты от целенаправленных атак**
15. **Что такое NGFW?**
16. **Организационная работа в сфере ИБ организации**
17. **Законы, регулирующие порядок работы с конфиденциальной информацией**
18. **Принципы информационной безопасности**
19. **Банковские угрозы ИБ**
20. **Что такое НСД? Методы доступа и основные угрозы для информации**
21. **Каким образом можно организовать перехват паролей?**
22. **Суть угрозы информации «Маскарад»**
23. **Что такое «незаконное использование привилегий»?**
24. **Разновидности основных угроз ИБ в локальных размерах**
25. **Степени и проявления ущерба для организации**
26. **Примеры актуальных внешних угроз при кибератаках на организации**
27. **Что такое «аудит ИБ в организации»?**
28. **Что такое «программное обеспечение»? Классификация**
29. **Жизненный цикл ПО**
30. **Дать определения «Дефект», «Уязвимость», «Эксплойт»**
31. **Примеры дефектов на этапе реализации**
32. **Классификация уязвимостей**
33. **Что такое OWASP?**
34. **Классификация OWASP**
35. **Что такое «внедрение SQL-кода»? Пример**
36. **Что такое CVE? Какие базы Вы знаете?**
37. **Основные векторы атак, используемые злоумышленниками**
38. **Методы поиска уязвимостей**
39. **Что такое Metasploit Framework?**
40. **Примеры использования Metasploit Framework**
41. **Статьи УК РФ в сфере компьютерных преступлений**
42. **Что такое тестирование на проникновение? Основные виды**
43. **Примеры международных методологий тестирования**
44. **Примеры дистрибутивов для пентеста**
45. **Что такое Nmap? Примеры команд**
46. **Назовите протоколы, работающие на портах: 21, 22, 23, 25, 53, 69, 80, 110, 443**
47. **Предназначение утилиты Network Miner**
48. **Что такое MASSCAN?**
49. **Примеры фильтров Wireshark**
50. **Функции утилиты Intercepter-NG**
51. **Что такое Burp Suite?**
52. **Примеры утилит для брутфорса**
53. **Примеры техник enumeration**
54. **Атака DNS zone transfer**
55. **Примеры утилит для SMB Enumeration**
56. **Предназначение HTTP Enumeration. Примеры утилит**
57. **Что такое технология «проксирования»? Примеры утилит**
58. **Какие бывают группы киберпреступников?**
59. **Кибератаки на телеком сектор**
60. **Кибератаки на энергетический сектор (примеры фреймворков)**
61. **Что такое тип кибератаки Supply Chain?**
62. **Примеры открытых военных киберопераций**
63. **Что такое JS-сниффер? Основные этапы заражения**
64. **Примеры кибератак на банковский сектор**
65. **Рассказать о любой хакерской группировке (цели, инструменты и т.д.)**
